### ISSUE TITLE
NPM says this features are implemented in the official AppDynamics agent

### ISSUE THREAD

**Issue by toxsick** [svrnm/appdynamics-nodejs-extras#8]
Hey there,

the npm package (https://www.npmjs.com/package/appdynamics-nodejs-extras) is now deprecated, because "The features provided by this extension are now available through the AppDynamics agent". Can you point me to any official documentation that explains how to implement this?

Thanks a lot and best regards

Hannes

**Comment by toxsick** [comment]
@svrnm just a quick info would help me out a lot, because I have to figure this out for a customer project. Thanks in advance!

Cheers
Hannes

**Comment by svrnm** [comment]
@toxsick you'll find the official docs here: https://docs.appdynamics.com/20.x/en/application-monitoring/configure-instrumentation/transaction-detection-rules/custom-match-rules/node-js-business-transaction-detection

**Comment by toxsick** [comment]
Damn, did not see that, thanks a lot!

regards
Hannes
